package at.ac.tuwien.fundify.adapters.in.rest.dto.enums;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum ECountryWebModel {
    AFGHANISTAN("Afghanistan"),
    EGYPT("Egypt"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    AZERBAIJAN("Azerbaijan"),
    ETHIOPIA("Ethiopia"),
    AUSTRALIA("Australia"),
    BAHAMAS("Bahamas"),
    BAHRAIN("Bahrain"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGIUM("Belgium"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BHUTAN("Bhutan"),
    BOLIVIA("Bolivia"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina"),
    BOTSWANA("Botswana"),
    BRAZIL("Brazil"),
    BRUNEI_DARUSSALAM("Brunei Darussalam"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CABO_VERDE("Cabo Verde"),
    CHILE("Chile"),
    CHINA("China"),
    COSTA_RICA("Costa Rica"),
    COTE_D_IVOIRE("Côte d'Ivoire"),
    DENMARK("Denmark"),
    GERMANY("Germany"),
    DOMINICA("Dominica"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    DJIBOUTI("Djibouti"),
    ECUADOR("Ecuador"),
    EL_SALVADOR("El Salvador"),
    ERITREA("Eritrea"),
    ESTONIA("Estonia"),
    ESWATINI("Eswatini"),
    FIJI("Fiji"),
    FINLAND("Finland"),
    FRANCE("France"),
    GABON("Gabon"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GHANA("Ghana"),
    GRENADA("Grenada"),
    GREECE("Greece"),
    GUATEMALA("Guatemala"),
    GUINEA("Guinea"),
    GUINEA_BISSAU("Guinea-Bissau"),
    GUYANA("Guyana"),
    HAITI("Haiti"),
    HONDURAS("Honduras"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAQ("Iraq"),
    IRAN("Iran"),
    IRELAND("Ireland"),
    ICELAND("Iceland"),
    ISRAEL("Israel"),
    ITALY("Italy"),
    JAMAICA("Jamaica"),
    JAPAN("Japan"),
    YEMEN("Yemen"),
    JORDAN("Jordan"),
    CAMBODIA("Cambodia"),
    CAMEROON("Cameroon"),
    CANADA("Canada"),
    KAZAKHSTAN("Kazakhstan"),
    QATAR("Qatar"),
    KENYA("Kenya"),
    KYRGYZSTAN("Kyrgyzstan"),
    KIRIBATI("Kiribati"),
    COLOMBIA("Colombia"),
    COMOROS("Comoros"),
    CONGO("Republic of the Congo"),
    CONGO_DRC("Democratic Republic of the Congo"),
    KOREA_DPR("Democratic People's Republic of Korea"),
    KOREA_REPUBLIC("Republic of Korea"),
    KOSOVO("Kosovo"),
    CROATIA("Croatia"),
    CUBA("Cuba"),
    KUWAIT("Kuwait"),
    LAOS("Lao People's Democratic Republic"),
    LESOTHO("Lesotho"),
    LATVIA("Latvia"),
    LEBANON("Lebanon"),
    LIBERIA("Liberia"),
    LIBYA("Libya"),
    LIECHTENSTEIN("Liechtenstein"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTA("Malta"),
    MOROCCO("Morocco"),
    MARSHALL_ISLANDS("Marshall Islands"),
    MAURITANIA("Mauritania"),
    MAURITIUS("Mauritius"),
    MEXICO("Mexico"),
    MICRONESIA("Federated States of Micronesia"),
    MOLDOVA("Republic of Moldova"),
    MONACO("Monaco"),
    MONGOLIA("Mongolia"),
    MONTENEGRO("Montenegro"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NEW_ZEALAND("New Zealand"),
    NICARAGUA("Nicaragua"),
    NETHERLANDS("Netherlands"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NORTH_MACEDONIA("North Macedonia"),
    NORWAY("Norway"),
    OMAN("Oman"),
    AUSTRIA("Austria"),
    PAKISTAN("Pakistan"),
    PALAU("Palau"),
    PANAMA("Panama"),
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    RWANDA("Rwanda"),
    ROMANIA("Romania"),
    RUSSIAN_FEDERATION("Russian Federation"),
    SOLOMON_ISLANDS("Solomon Islands"),
    ZAMBIA("Zambia"),
    SAMOA("Samoa"),
    SAN_MARINO("San Marino"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
    SAUDI_ARABIA("Saudi Arabia"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    ZIMBABWE("Zimbabwe"),
    SINGAPORE("Singapore"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOMALIA("Somalia"),
    SPAIN("Spain"),
    SRI_LANKA("Sri Lanka"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    SAINT_LUCIA("Saint Lucia"),
    SAINT_VINCENT_AND_GRENADINES("Saint Vincent and the Grenadines"),
    SOUTH_AFRICA("South Africa"),
    SUDAN("Sudan"),
    SOUTH_SUDAN("South Sudan"),
    SURINAME("Suriname"),
    SYRIAN_ARAB_REPUBLIC("Syrian Arab Republic"),
    TAJIKISTAN("Tajikistan"),
    TANZANIA("United Republic of Tanzania"),
    THAILAND("Thailand"),
    TIMOR_LESTE("Timor-Leste"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    CHAD("Chad"),
    CZECHIA("Czechia"),
    TUNISIA("Tunisia"),
    TURKEY("Türkiye"),
    TURKMENISTAN("Turkmenistan"),
    TUVALU("Tuvalu"),
    UGANDA("Uganda"),
    UKRAINE("Ukraine"),
    HUNGARY("Hungary"),
    URUGUAY("Uruguay"),
    UZBEKISTAN("Uzbekistan"),
    VANUATU("Vanuatu"),
    VATICAN_CITY("Vatican City"),
    VENEZUELA("Venezuela"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    UNITED_STATES("United States"),
    UNITED_KINGDOM("United Kingdom"),
    VIETNAM("Vietnam"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    CYPRUS("Cyprus");

    private final String value;

    public static ECountryWebModel fromString(String value) {
        for (ECountryWebModel e : ECountryWebModel.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        return null;
    }

    @JsonValue
    public String getValue() {
        return value;
    }
}