package at.ac.tuwien.fundify.domain.common;


public enum EFundingCharacteristic {
    INTERNATIONAL_PROGRAMME,
    BILATERAL_PROGRAMME,
    NATIONAL_PROGRAMME,
    INDIVIDUAL_PROJECT,
    CONSORTIUM,
    SCIENTIFIC_PROGRAMME,
    COOPERATIVE_PROGRAMME,
    PERSONAL_GRANT,
    PROJECT_FUNDING,
    INFRASTRUCTURE,
    NETWORKING,
    MOBILITY_PROGRAMME
}
