package at.ac.tuwien.fundify.domain.common;

public enum ETargetGroup {
    UNIVERSITY,
    UNIVERSITY_OF_APPLIED_SCIENCES,
    PRIVATE_UNIVERSITY,
    RESEARCH_INSTITUTE,
    COMPANY,
    PRIVATE_NON_PROFIT,
    INDEPENDENT_RESEARCHER,
    GOVERNMENT
}
