export const ROUTER_LINKS = {
  BASE: '',
  HOME: 'home',
  CONTACT: 'contact',
  IMPRESSUM: 'impressum',
  SETTINGS: 'settings',
  FUNDINGS: 'fundings',
  ANNOTATIONS: 'annotations',
  INSTITUTIONS: 'institutions',
  CALLS: 'calls',
  CALL_ID: 'calls/:id',
  CALL_NEW: 'calls/new',
  PROGRAMS: 'programs',
  PROGRAM_ID: 'programs/:id',
  PROGRAM_EDIT: 'programs/:id/edit',
  PROGRAM_NEW: 'programs/new',
  CREATE_NEW_PROGRAM: 'fundings/programs/new',
  FUNDERS: 'funders',
  FUNDER_ID: 'funders/:id',
  FUNDER_EDIT: 'funders/:id/edit',
  FUNDER_NEW: 'funders/new',
  CREATE_NEW_FUNDER: '/institutions/funders/new',

  UNIVERSITIES: 'universities',
  UNIVERSITY_ID: 'universities/:id',
  UNIVERSITY_NEW: 'universities/new',
  UNIVERSITY_EDIT: 'universities/:id/edit',

  EDIT: 'edit',
  PREVIEW: 'preview',
  ANNOTATE: 'annotate',
  PAGE_NOT_FOUND: 'page-not-found',
  NOT_AUTHORIZED: 'not-authorized',
  LOGIN: '/auth',

  USERS: 'users',
  USER_PERMISSIONS: 'permissions',
} as const;
