package at.ac.tuwien.fundify.domain.funding.vo.enums;


public enum ECareerStage {
    EXPERTS,
    STUDENTS,
    DOCTORAL_STUDENTS,
    EARLY_STAGE_RESEARCHERS,
    MID_CAREER_RESEARCHERS,
    ESTABLISHED_RESEARCHERS,
    UNDERGRADUATE_STUDENTS,
    GRADUATE_STUDENTS,
    POSTGRADUATE_STUDENTS,
    POSTDOCTORAL_RESEARCHERS,
    SCIENTISTS,
    SCIENTIFIC_INSTITUTION
}
