export const CALLS_CONSTANTS = {
  SEARCH_FIELD_LABEL: 'Search...',
  SEARCH_FIELD_PLACEHOLDER: 'Search by id, name, program or funder',
  SUBSCRIPTION_STATUS_SUBSCRIBED: 'SUBSCRIBED',
  SUBSCRIPTION_STATUS_UNSUBSCRIBED: 'UNSUBSCRIBED',
  TABLE_COLUMNS: [
    { header: 'Acronym', field: 'acronym' },
    { header: 'Name', field: 'name' },
    { header: 'Part Of', field: 'partOf' },
    { header: 'Funder', field: 'funder' },
    { header: 'Status', field: 'status' },
    { header: 'Last updated', field: 'lastUpdatedAt' },
  ],
  ADD_BUTTON_LABEL: 'new',
};

export const CALL_ANNOTATION_LIST_CONSTANTS = {
  SEARCH_FIELD_LABEL: 'Search...',
  SEARCH_FIELD_PLACEHOLDER: 'Search by call-, program- or funder-name',
  TABLE_COLUMNS: [
    { header: 'Name', field: 'name' },
    { header: 'Part Of', field: 'partOf' },
    { header: 'Funder', field: 'funder' },
    { header: 'Call Status', field: 'callStatus' },
    { header: 'Annotation Status', field: 'status' },
    { header: 'Last updated', field: 'lastUpdatedAt' },
    { header: 'Updated By', field: 'lastUpdatedBy' },
  ],
};

export const CALL_DETAILS_CONSTANTS = {
  TITLE: 'Call Details',
  TABLE_HEADERS: ['label', 'value'],
  NO_DATA_MESSAGE: 'No Data available',
  FUNDING_TYPE_LABEL: 'Funding Type',
  APPlICATION_LANGUAGE_LABEL: 'Application Language',
  RIS_ID_LABEL: 'RIS Synergy ID',
  RIS_ID_PLACEHOLDER: 'Enter RIS Synergy ID',
  PART_OF_LABEL: 'Part Of',
  PART_OF_PLACEHOLDER: 'Search Program...',
  CREATE_NEW_PROGRAM_LABEL: 'Create New Program',
  NO_PROGRAMS_SELECTED_LABEL: 'no program selected',
  NAME_LABEL: 'Name',
  NAME_PLACEHOLDER: 'Enter Name for Call',
  ACRONYM_LABEL: 'Acronym',
  ACRONYM_PLACEHOLDER: 'Enter Acronym for Call',
  TARGET_GROUP_LABEL: 'Target Group',
  TARGET_GROUP_SPECIFIED_LABEL: 'Target Group Specified',
  CAREER_STAGE_LABEL: 'Career Stage',
  THEMATIC_ORIENTATIONS_LABEL: 'Thematic Orientation',
  SUBJECT_LABEL: 'Subject',
  DESCRIPTION_LABEL: 'Description',
  DESCRIPTION_PLACEHOLDER: 'Enter Description for Call',
  CHARACTERISTICS_LABEL: 'Characteristics',
  LEGAL_TYPE_LABEL: 'Legal Type',
  FUNDING_SCHEMES_LABEL: 'Funding Scheme',
  ELIGIBLE_APPLICANTS_LABEL: 'Eligible Applicants',
  ELIGIBLE_APPLICANTS_PLACEHOLDER: 'Details about Eligible Applicants',
  ELIGIBLE_APPLICANTS_SCOPE_LABEL: 'Eligible Applicants Scope',
  ELIGIBLE_APPLICANTS_REGION_LABEL: 'Eligible Applicants Region',
  MIN_PROJECT_VOLUME_LABEL: 'Min Project Volume',
  MAX_PROJECT_VOLUME_LABEL: 'Max Project Volume',
  CALL_VOLUME_PROJCETS_LABEL: 'Call Volume Projects (Max.)',
  CALL_VOLUME_AMOUNT_LABEL: 'Call Volume Amount',
  MIN_PROJECT_DURATION_LABEL: 'Min Project Duration',
  MAX_PROJECT_DURATION_LABEL: 'Max Project Duration',
  FULLY_FUNDED_LABEL: 'Fully funded?',
  MIN_INKIND_LABEL: 'Min Inkind [%]',
  INKIND_DETAILS_LABEL: 'Inkind Details',
  INKIND_DETAILS_PLACEHOLDER: 'Enter Inkind Details',
  MAX_OVERHEAD_LABEL: 'Max Overhead [%]',
  OVERHEAD_DETAILS_LABEL: 'Overhead Details',
  OVERHEAD_DETAILS_PLACEHOLDER: 'Enter Overhead Details',
  DECISION_PROCESS_DETAILS_LABEL: 'Decision Process Details',
  DECISION_PROCESS_LABEL: 'Decision Process',
  REPORTING_PERIODS_LABEL: 'Reporting Periods',
  REPORTING_PERIODS_PLACEHOLDER: 'Enter Reporting Periods',
  STAGES_LABEL: 'Call Stages',
  CALL_STAGE_LABEL: 'Call Stage',
  CALL_STAGE_DETAILS_LABEL: 'Description',
  CALL_STAGE_DATE_RANGE_LABEL: 'Date Range',
  MODE_OF_SUBMISSION_LABEL: 'Mode of Submission',
  DMP_REQUIRED_LABEL: 'DMP Required?',
  DMP_GUIDELINES_LABEL: 'DMP Guidelines',
  DMP_GUIDELINES_PLACEHOLDER: 'Enter Url for DMP Guidelines',
  PROJECT_START_DETAILS_LABEL: 'Project Start Details',
  PROJECT_START_DETAILS_PLACEHOLDER: 'Enter Project Start Details',
  PROJECT_START_LABEL: 'Project Start',
  WEBSITE_LABEL: 'Website',
  WEBSITE_PLACEHOLDER: 'Url for Website',
  MAIN_FUNDER_LABEL: 'Funder',
  JOINT_CALL_PARTNER_LABEL: 'Joint Call Partners',
  JOINT_CALL_PARTNER_PLACEHOLDER: 'Search for Joint Call Partners',
  NO_JOINT_CALL_PARTNERS_SELECTED_LABEL: 'no joint call partners selected',
  CONTACTS_LABEL: 'Contacts',
  CONTACT_SUB_LABELS: ['Name', 'Email', 'Phone'],
  DURATION_SUB_LABELS: ['Months', 'Days'],
  PLACEHOLDER: ' - ',
  PUBLISH_DISABLED_TOOLTIP: 'Call is not valid',
  ERRORS: {
    GENERIC_ERROR: 'An unexpected error occurred.',
  },
  CREATION_SUCCESS: 'A new call has been successfully created.',
  UPDATE_SUCCESS: 'The call has successfully been updated.',
  CALL_SUBSCRIBED: 'You have successfully subscribed to the call',
  CALL_UNSUBSCRIBED: 'You have successfully unsubscribed from the call',
};
