export const UNIVERSITIES_CONSTANTS = {
  SEARCH_FIELD_LABEL: 'Search...',
  ADD_BUTTON_LABEL: 'new',
  SEARCH_FIELD_PLACEHOLDER: 'Search by id, acronym or name',
  TABLE_COLUMNS: [
    { header: 'Acronym', field: 'acronym' },
    { header: 'Name', field: 'name' },
    { header: 'Website', field: 'website' },
  ],
};

export const UNIVERSITY_DETAILS_CONSTANTS = {
  TITLE: 'University Details',
  NO_DATA_MESSAGE: 'No Data available',
  NAME_LABEL: 'Name',
  NAME_PLACEHOLDER: 'Enter University Name',
  RIS_ID_LABEL: 'RisId',
  RIS_ID_PLACEHOLDER: 'Enter RisId',
  ACRONYM_LABEL: 'Acronym',
  ACRONYM_PLACEHOLDER: 'Enter Acronym',
  MAIL_DOMAIN_LABEL: 'Email Domain',
  MAIL_DOMAIN_PLACEHOLDER: 'Enter Email Domain',
  WEBSITE_LABEL: 'Website',
  WEBSITE_PLACEHOLDER: 'Enter URL',
  ADDRESS_LABEL: 'Address',
  STREET_LINE_LABEL: 'Street',
  STREET_LINE_PLACEHOLDER: 'Enter Street',
  CITY_LABEL: 'City',
  CITY_PLACEHOLDER: 'Enter City',
  POSTAL_CODE_LABEL: 'Postal Code',
  POSTAL_CODE_PLACEHOLDER: 'Enter Postal Code',
  COUNTRY_CODE_LABEL: 'Country Code',
  COUNTRY_CODE_PLACEHOLDER: 'Enter Country Code',
  PHONE_LABEL: 'Phone',
  PHONE_PLACEHOLDER: 'Enter Phone Number',
  SUBMISSION_SYSTEM_LABEL: 'Submission System',
  SUBMISSION_SYSTEM_PLACEHOLDER: 'Enter URL',
  CROSSREF_DOI_LABEL: 'Crossref DOI',
  CROSSREF_DOI_PLACEHOLDER: 'Enter CrossRef DOI',
  PLACEHOLDER: '-',
  ERRORS: {
    GENERIC_ERROR: 'An unexpected error occurred.',
  },
  CREATION_SUCCESS: 'A new university entry has been successfully created.',
  UPDATE_SUCCESS: 'The university has successfully been updated.',
  NO_UNIVERSITY_DETAILS: 'No university details available.',
};
