export const FUNDERS_CONSTANTS = {
  SEARCH_FIELD_LABEL: 'Search...',
  ADD_BUTTON_LABEL: 'new',
  SEARCH_FIELD_PLACEHOLDER: 'Search by id, acronym or name',
  TABLE_COLUMNS: [
    { header: 'Acronym', field: 'acronym' },
    { header: 'Name', field: 'name' },
    { header: 'Crossref DOI', field: 'crossRefDoi' },
    { header: 'Website', field: 'website' },
  ],
};

export const FUNDER_DETAILS_CONSTANTS = {
  TITLE: 'Funder Details',
  NO_DATA_MESSAGE: 'No Data available',
  NAME_LABEL: 'Name',
  NAME_PLACEHOLDER: 'Enter Funder Name',
  ACRONYM_LABEL: 'Acronym',
  ACRONYM_PLACEHOLDER: 'Enter Acronym',
  CROSSREF_DOI_LABEL: 'Crossref DOI',
  CROSSREF_DOI_PLACEHOLDER: 'Enter CrossRef DOI',
  ADDRESS_LABEL: 'Address',
  ADDRESS_PLACEHOLDER: 'Enter Address',
  STREET_LINE_LABEL: 'Street',
  STREET_LINE_PLACEHOLDER: 'Enter Street',
  CITY_LABEL: 'City',
  CITY_PLACEHOLDER: 'Enter City',
  POSTAL_CODE_LABEL: 'Postal Code',
  POSTAL_CODE_PLACEHOLDER: 'Enter Postal Code',
  COUNTRY_CODE_LABEL: 'Country Code',
  COUNTRY_CODE_PLACEHOLDER: 'Enter Country Code',
  RIS_ID_LABEL: 'RisId',
  RIS_ID_PLACEHOLDER: 'Enter RisId',
  PHONE_LABEL: 'Phone',
  PHONE_PLACEHOLDER: 'Enter Phone Number',
  WEBSITE_LABEL: 'Website',
  WEBSITE_PLACEHOLDER: 'Enter URL',
  SUBMISSION_SYSTEM_LABEL: 'Submission System',
  SUBMISSION_SYSTEM_PLACEHOLDER: 'Enter URL',
  EXTERNALLY_ADMINISTERED_LABEL: 'Externally Administered',
  PLACEHOLDER: '-',
  ERRORS: {
    GENERIC_ERROR: 'An unexpected error occurred.',
  },
  CREATION_SUCCESS: 'A new funder has been successfully created.',
  UPDATE_SUCCESS: 'The funder has successfully been updated.',
  NO_FUNDER_DETAILS: 'No funder details available',
};
